-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: db/changelog/db.changelog-master.yaml
-- Ran at: 4/24/26, 11:14 PM
-- Against: null@offline:postgresql
-- Liquibase version: 4.31.1
-- *********************************************************************

-- Changeset db/changelog/changes/001-create-tables.yaml::001-create-clients::bp-team
CREATE TABLE clients (client_id VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, gender VARCHAR(255) NOT NULL, age INTEGER NOT NULL, identification VARCHAR(255) NOT NULL, address VARCHAR(255), phone VARCHAR(255), password VARCHAR(255) NOT NULL, status VARCHAR(16) NOT NULL, created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, CONSTRAINT pk_clients PRIMARY KEY (client_id), CONSTRAINT uk_clients_identification UNIQUE (identification));

-- Changeset db/changelog/changes/001-create-tables.yaml::001-create-accounts::bp-team
CREATE TABLE accounts (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, account_number VARCHAR(255) NOT NULL, account_type VARCHAR(16) NOT NULL, initial_balance numeric(19, 2) NOT NULL, current_balance numeric(19, 2) NOT NULL, status VARCHAR(16) NOT NULL, client_id VARCHAR(255) NOT NULL, created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, CONSTRAINT pk_accounts PRIMARY KEY (id), CONSTRAINT fk_accounts_client FOREIGN KEY (client_id) REFERENCES clients(client_id), CONSTRAINT uk_accounts_account_number UNIQUE (account_number));

CREATE INDEX ix_accounts_client_id ON accounts(client_id);

-- Changeset db/changelog/changes/001-create-tables.yaml::001-create-movements::bp-team
CREATE TABLE movements (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, movement_type VARCHAR(16) NOT NULL, movement_value numeric(19, 2) NOT NULL, balance numeric(19, 2) NOT NULL, account_id BIGINT NOT NULL, created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, CONSTRAINT pk_movements PRIMARY KEY (id), CONSTRAINT fk_movements_account FOREIGN KEY (account_id) REFERENCES accounts(id));

CREATE INDEX ix_movements_account_id ON movements(account_id);

CREATE INDEX ix_movements_date ON movements(date);

-- Changeset db/changelog/changes/002-seed-data.yaml::002-seed-clients::bp-team
INSERT INTO clients (client_id, name, gender, age, identification, address, phone, password, status, created_at, updated_at) VALUES ('jlema', 'Jose Lema', 'MALE', 35, '1700000001', 'Otavalo sn y principal', '098254785', '$2a$10$clJTNeMYFWoSzXi9FQ9dyeV9EfVFqwVjwmucJPNBKV5Xht85o4Q3m', 'ACTIVE', NOW(), NOW());

INSERT INTO clients (client_id, name, gender, age, identification, address, phone, password, status, created_at, updated_at) VALUES ('mmontalvo', 'Marianela Montalvo', 'FEMALE', 32, '1700000002', 'Amazonas y NNUU', '097548965', '$2a$10$l8hcEWSCN.hNWhY1oQQVTeuAmfk0cNvcGBcbNhiIXTkAkMRAAeea.', 'ACTIVE', NOW(), NOW());

INSERT INTO clients (client_id, name, gender, age, identification, address, phone, password, status, created_at, updated_at) VALUES ('josorio', 'Juan Osorio', 'MALE', 40, '1700000003', '13 junio y Equinoccial', '098874587', '$2a$10$ug0SMm0P.WHfhnlRTim0Jur70QK35D5qtY0Bzn5TtRWQnFHLDFOHa', 'ACTIVE', NOW(), NOW());

-- Changeset db/changelog/changes/002-seed-data.yaml::002-seed-accounts::bp-team
INSERT INTO accounts (account_number, account_type, initial_balance, current_balance, status, client_id, created_at, updated_at) VALUES ('478758', 'SAVINGS', 2000.0, 1425.0, 'ACTIVE', 'jlema', NOW(), NOW());

INSERT INTO accounts (account_number, account_type, initial_balance, current_balance, status, client_id, created_at, updated_at) VALUES ('225487', 'CHECKING', 100.0, 700.0, 'ACTIVE', 'mmontalvo', NOW(), NOW());

INSERT INTO accounts (account_number, account_type, initial_balance, current_balance, status, client_id, created_at, updated_at) VALUES ('495878', 'SAVINGS', 0.0, 150.0, 'ACTIVE', 'josorio', NOW(), NOW());

INSERT INTO accounts (account_number, account_type, initial_balance, current_balance, status, client_id, created_at, updated_at) VALUES ('496825', 'SAVINGS', 540.0, 0.0, 'ACTIVE', 'mmontalvo', NOW(), NOW());

INSERT INTO accounts (account_number, account_type, initial_balance, current_balance, status, client_id, created_at, updated_at) VALUES ('585545', 'CHECKING', 1000.0, 1000.0, 'ACTIVE', 'jlema', NOW(), NOW());

-- Changeset db/changelog/changes/002-seed-data.yaml::002-seed-movements::bp-team
INSERT INTO movements (date, movement_type, movement_value, balance, account_id, created_at, updated_at)
SELECT NOW(), 'WITHDRAWAL', -575.00, 1425.00, id, NOW(), NOW()
FROM accounts WHERE account_number = '478758';

INSERT INTO movements (date, movement_type, movement_value, balance, account_id, created_at, updated_at)
SELECT NOW(), 'DEPOSIT', 600.00, 700.00, id, NOW(), NOW()
FROM accounts WHERE account_number = '225487';

INSERT INTO movements (date, movement_type, movement_value, balance, account_id, created_at, updated_at)
SELECT NOW(), 'DEPOSIT', 150.00, 150.00, id, NOW(), NOW()
FROM accounts WHERE account_number = '495878';

INSERT INTO movements (date, movement_type, movement_value, balance, account_id, created_at, updated_at)
SELECT NOW(), 'WITHDRAWAL', -540.00, 0.00, id, NOW(), NOW()
FROM accounts WHERE account_number = '496825';

